# Generated by Django 5.2 on 2025-04-26 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
