# Generated by Django 5.1.7 on 2025-04-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companions', '0003_alter_customuser_city_alter_customuser_phone_and_more'),
        ('companions', '0004_customuser_name'),
    ]

    operations = [
    ]
